/**
 * DevOceanAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPermission } from './userPermission';


export interface User { 
    userName?: string | null;
    email?: string | null;
    permissions?: UserPermission;
}

